# Common config fields, showing default values
input:
  label: "test_csv"
  csv:
    paths:
      - /root/batch2stream/benthos/sensorInput/*.csv
    parse_header_row: true
    delete_on_finish: true
    delimiter: ','
    lazy_quotes: false
output:
  label: "test_redpanda"
  kafka_franz:
    seed_brokers: ["localhost:19092"] 
    topic: "sensor_csv" 
    max_in_flight: 1